language: perl

perl:
    - "5.30"

addons:
    apt:
        packages:
            - libdb-dev
            - libbio-perl-perl
            - libxml-simple-perl

install:
    - "export PATH=$PWD/bin:$PATH"

script:
    - "prokka --version"
    - "prokka --help"
    - "! prokka --doesnotexist"
    - "prokka --depends"
    - "prokka --setupdb"
    - "prokka --listdb"
    - "prokka --cpus 2 --outdir asm --prefix asm test/plasmid.fna"
    - "grep '>' asm/asm.fna"
    - "prokka --cleandb"
